### ISSUE TITLE
On Storybook not working

### ISSUE THREAD

**Issue by andersravn** [johnajacob/nextjs-tailwindcss-storybook#6]
Consider reading this post: https://dev.to/0xcap/nextjs-typescript-tailwindcss-storybook-project-setup-4clj.

Particularly the step about postcss.config.js:
```js
module.exports = {
  plugins: {
    tailwindcss: {}, 
    "postcss-preset-env": {}
  }
};
```

**Comment by johnajacob** [comment]
@andersravn Thanks! Updated the repo. Sorry for the delay
